### ISSUE TITLE
这不就是ai 强国吗

### ISSUE THREAD

**Issue by hxhsy** [Gingmzmzx/auto-xxqg#15]
//在提交前请先查看issues，如果有相同问题就不要提交issues了
//提出的issues通常会在晚上回答，请耐心等待。
//请先删去这前三行注释部分

1、请简述您遇到的问题

2、请说明您使用的版本

3、（选填）提交截图或视频

4、紧急程度（默认为"中"）

**Comment by Gingmzmzx** [comment]
是基于aiqiangguo做的，但后续的方向功能等随着更新肯定会不同
