### ISSUE TITLE
循环学习

### ISSUE THREAD

**Issue by blank-psy** [Gingmzmzx/auto-xxqg#3]
如果学习文章没有完成，会学习三个随机项目里的前n篇文章，而按积分学习设置是学一篇文章30秒就退出学习下一篇文章，导致文章积分不足重新学习学过的文章，就陷入了死循环，和Ai强国出现的问题一样，在Ai强国已经关闭的9#议题有人提出了解决方法，不知道能行不，以下是复制的原文：
可以自己调整，我调整了一下文章或视频的获取方式，你可以参考一下：
`for (let i = 0; i < vCount;) {
let articles = id("general_card_title_id").find();
console.log("找到文章：" + articles.length)
for (let article of articles) {
//查找是否存在播报，如果存在则为文章
let report = article.parent().parent().findOne(text("播报"));
if (!report) {
let title = article.text();
let flag = Utils.getLearnedArticle(title, date_string, user);
if (!flag) {
console.log("观看第【" + (i + 1) + "】个视频：" + title);
if (click(title)) {
let n = 0;
while (!textContains("欢迎发表你的观点").exists()) {//如果没有找到评论框则认为没有进入文章界面，一直等待
Utils.delay(1);
console.warn("正在等待加载视频界面...");
if (n > 3) {//等待超过3秒则认为进入了专题界面，退出
console.warn("没找到评论框!该界面非文章界面!");
zt_flag = true;
break;
}
n++;
}
![Screenshot_20210218_195902.jpg](https://user-images.githubusercontent.com/78307952/108354302-38aa3500-7224-11eb-9064-5710167a5c3d.jpg)

**Comment by Gingmzmzx** [comment]
好的好的，谢谢谢谢，非常感谢

**Comment by Gingmzmzx** [comment]
我这里是全部可以正常执行的，您指的是时长不够吗？这个可以调的

**Comment by Gingmzmzx** [comment]
aTime变量，阅读文章的时长，其实我以前的版本都是60秒

**Comment by blank-psy** [comment]
60秒的更好，因为不用翻那么多篇文章

**Comment by Gingmzmzx** [comment]
那我下一个版本v2.4.4就考虑恢复60秒

**Comment by blank-psy** [comment]
> 那我下一个版本v2.4.4就考虑恢复60秒

你的网站not found 好几天了

**Comment by Gingmzmzx** [comment]
由于ngrok映射服务最近无法认证，我更换了服务器和域名。新域名 http://xzy.9gz.xyz/ 我现在其实并不想宣传这个域名，因为由于云服务器php的设置，我的网站还存在着很大的问题，例如:有些页面无法显示，以及其他严重的问题。

**Comment by Dullxxs** [comment]
> 
> 
> 由于ngrok映射服务最近无法认证，我更换了服务器和域名。新域名 http://xzy.9gz.xyz/ 我现在其实并不想宣传这个域名，因为由于云服务器php的设置，我的网站还存在着很大的问题，例如:有些页面无法显示，以及其他严重的问题。

可以去wikihost上买个虚拟空间，70一年，我拿来挂WordPress还是蛮快的。

**Comment by blank-psy** [comment]
> 由于ngrok映射服务最近无法认证，我更换了服务器和域名。新域名 http://xzy.9gz.xyz/ 我现在其实并不想宣传这个域名，因为由于云服务器php的设置，我的网站还存在着很大的问题，例如:有些页面无法显示，以及其他严重的问题。

赞赏，绵薄之力

**Comment by Gingmzmzx** [comment]
@blank-psy 谢谢谢谢，感谢您的赞助🙏🏻

**Comment by Gingmzmzx** [comment]
@blank-psy 刚看微信，您这捐了那么多呀，这给您退一些吧，太多了，我承担不起！

**Comment by blank-psy** [comment]
> @blank-psy 刚看微信，您这捐了那么多呀，这给您退一些吧，太多了，我承担不起！

支持一下，别介意，省时间更重要

**Comment by Gingmzmzx** [comment]
感谢感谢🙏🏻我已经打算租个服务器了
