### ISSUE TITLE
直接运行main报错，谢谢指点

### ISSUE THREAD

**Issue by 85524365** [Gingmzmzx/auto-xxqg#6]
22:02:08.437/E: Wrapped com.stardust.pio.UncheckedIOException: java.io.FileNotFoundException: /storage/emulated/0/脚本/auto-xxqg-main/if.txt (No such file or directory) (/storage/emulated/0/脚本/auto-xxqg-main/main.js#10)
Wrapped com.stardust.pio.UncheckedIOException: java.io.FileNotFoundException: /storage/emulated/0/脚本/auto-xxqg-main/if.txt (No such file or directory)
    at /storage/emulated/0/脚本/auto-xxqg-main/main.js:10:0

**Comment by Gingmzmzx** [comment]
噢噢噢，这是新版本的一个bug，原因是这样的：我想添加一个首次打开会提示一些内容，而以后打开就不会提示了。这个功能在我本地运行代码是完全没有问题的，但是我打包后发现这个功能无法实现，考虑到有些用户是直接下载apk，所以我暂时注释了这个功能。

**Comment by Gingmzmzx** [comment]
把第十行注释掉就行了，我在注释时忘了注释第十行

**Comment by 85524365** [comment]
大神级别的，羡羡
