### ISSUE TITLE
观看新闻时，希望添加防息屏弹窗

### ISSUE THREAD

**Issue by shuaiqingm** [Gingmzmzx/auto-xxqg#60]
观看新闻时，希望添加防息屏弹窗，有些新闻的时长根本就没有60秒，会造成熄屏，无法再运行程序。
另外一个，观看视频的读秒改为文章那样，5秒一次。现在是1秒一次的。

**Comment by Gingmzmzx** [comment]
好建议，我会改的

**Comment by Gingmzmzx** [comment]
v2.7.0已经添加
