### ISSUE TITLE
我发你邮箱.json格式的文件，不是不给你弄应当，是我真不懂这些东西。

### ISSUE THREAD

**Issue by taslord** [Gingmzmzx/auto-xxqg#64]
//在提交前请先查看issues，如果有相同问题就不要提交issues了
//提出的issues通常会在晚上回答，请耐心等待。
//请先删去这前三行注释部分

1、请简述您遇到的问题

2、请说明您使用的版本

3、（选填）提交截图或视频

4、紧急程度（默认为"中"）

**Comment by Gingmzmzx** [comment]
json格式更好，我可以直接用tikuCommon.js直接导入，excel也可以转换为csv然后导入
