### ISSUE TITLE
Cannot call method “toString” of underfined

### ISSUE THREAD

**Issue by HDZZY** [Gingmzmzx/auto-xxqg#68]
1、请简述您遇到的问题
华为mate40 鸿蒙版和mate10在最近点击运行时总是失败，点击运行直接出行截图所示问题

2、请说明您使用的版本
2.7和2.6.02均有此类问题

3、（选填）提交截图或视频
![Screenshot_20210731_235016_org autojs autojs](https://user-images.githubusercontent.com/87889070/127745387-012106f7-bf71-44a1-96f1-d2538630a759.jpg)
![Screenshot_20210731_235025_org autojs autojs](https://user-images.githubusercontent.com/87889070/127745388-980b7071-b325-4ab6-9855-72c2405b920e.jpg)

4、紧急程度（默认为"中"）

**Comment by Gingmzmzx** [comment]
这里注意几点
1.不要用autojs pro，最好是用4.1.1
2.导入代码要导入到项目中，不是说直接复制到脚本文件夹
![Screenshot_20210801-000841](https://user-images.githubusercontent.com/49107602/127745843-7b06b6b4-4619-4a25-a811-656791fb01a6.jpg)
提示一下，项目就是有蓝色的那个图表的苹果商店的那个东西

**Comment by HDZZY** [comment]
在我的另一个手机中，我是遵行“导入代码要导入到项目中，而非直接复制到脚本文件夹”
而且用的也确实是autojs4.1.1那个里面会显示“有蓝色的那个图表的苹果商店的那个东西”，依旧有问题，非常奇怪

**Comment by Gingmzmzx** [comment]
1.请您检查v2.7.0的main.js中第一行是否与我提供的源代码一致
2.请您检查v2.7.0的main.js中126至178行是否与我提供的源代码一致

**Comment by Gingmzmzx** [comment]
据报错看，是因为获取不到ui中的input导致的，这个问题要是实在解决不了，重启可以试试，因为autojs的很多问题都可以通过重启解决

**Comment by HDZZY** [comment]
- 咋说嘞，我完全么有修改您里边的代码.....

**Comment by Gingmzmzx** [comment]
重启一下试试，实在不行应该是autojs的问题，就换个安装包重装一下，我给你发一个吧

**Comment by HDZZY** [comment]
重启也没用，但是我发现2.7以前的版本的没有这个问题的，就2.7有，完全无法运行，非常奇怪

**Comment by gxylfm** [comment]
我也发现这个问题了，重启几次软件就好了。

**Comment by HDZZY** [comment]
@gxylfm 那你比我幸运多了，我再怎样重启，哪怕手机关机，杀掉所有后台，隔断时间再重启也是没用的。也尝试更换了下auto.js的版本，也是不行的。最后无奈，只能回退到2.6.0.2咯

**Comment by HDZZY** [comment]
Anyway，2.7里可能确实存在着一些非常神奇的bug，我的两个手机也不行。。。

**Comment by HDZZY** [comment]
幸福，我再怎样重启也无法使用。所以，我只能回退到到2.6.0.2继续使用了。。。

发件人: gxylfm
发送时间: 2021年8月1日 14:35
收件人: Gingmzmzx/auto-xxqg
抄送: HDZZY; Author
主题: Re: [Gingmzmzx/auto-xxqg] Cannot call method “toString” of underfined (#68)

我也发现这个问题了，重启几次软件就好了。

**Comment by Gingmzmzx** [comment]
@HDZZY 你试试我这个，毕竟alpha版bug还是很多的
复制这段内容后打开百度网盘手机App，操作更方便哦 链接:https://pan.baidu.com/s/1Jw1dr7nKIommtrnAt6nb5Q 提取码:4os8

**Comment by HDZZY** [comment]
@Gingmzmzx 依旧没用，我甚至还在P30上也试了一下，还是不行，依旧显示同样的问题...

**Comment by HDZZY** [comment]
哦！我还在虚拟机上试了试也存在共同的问题哦...

**Comment by Gingmzmzx** [comment]
您直接下载打包好的apk不行吗？你们不看releases吗：[https://github.com/Gingmzmzx/auto-xxqg/releases/](url)

**Comment by HDZZY** [comment]
Soooo soooooooorry! 这就看！
