### ISSUE TITLE
app提示的下载更新的地址404

### ISSUE THREAD

**Issue by traceless0929** [Gingmzmzx/auto-xxqg#69]
http://xzy.9gz.xyz/web/xxqg/
提示去这里下载 但是进去404 是还有什么隐藏规则要跟上版本号之类的吗

**Comment by Gingmzmzx** [comment]
地址；http://xzy.center/web/xxqg，那个地址不用了所以404

**Comment by traceless0929** [comment]
> 地址；http://xzy.center/web/xxqg ，那个地址不用了所以404

回复竟然那么快，谢谢我在强国题库里找到链接下载了

**Comment by traceless0929** [comment]
> 地址；http://xzy.center/web/xxqg ，那个地址不用了所以404

不过下下来alpha版本还是提示有更新 依旧是这个网站

**Comment by traceless0929** [comment]
> 地址；http://xzy.center/web/xxqg ，那个地址不用了所以404

加群了 这下真的找到了

**Comment by Gingmzmzx** [comment]
现在不会404了
